workspace:
  base: /srv/app
  path: src

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  build:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install
      - yarn run clean
      - yarn run build
      - yarn run release

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_access_key, s3_secret_key ]
    bucket: releases
    endpoint: https://storage.gitea.io
    path_style: true
    strip_prefix: dist/
    source: dist/master.tar.gz
    target: /theme
    when:
      event: [ push ]
      branch: [ master ]

  trigger:
    image: plugins/downstream:1
    pull: true
    secrets: [ downstream_token ]
    server: https://drone.gitea.io
    repositories:
      - go-gitea/website
      - go-gitea/blog
      - go-gitea/docs
      - go-gitea/redirects
    when:
      event: [ push ]
      branch: [ master ]

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
